model: 'Cycle_GAN'
dataset_name: 'Cityscapes'
gen_in_channels: 3
dis_in_channels: 3
# generator part
data_path: '/mnt/city_gan'
input_size: 256

workers: 4
epochs: 100
batch_size: 1

save_freq: 1
save_dir: './saved'
gpus: -1

# models
gen_module: 'resnet'

dis_module: 'path_gan'

gan_mode: 'lsgan'
lambda_L1: 10
lambda_idt: 2

optimizer: 'adam'
learning_rate: 2e-3

experimental_option:
  os: 'windows'
  callbacks:
    - 'SWA'